# Generated by Django 6.0 on 2026-02-16 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_notification'),
        ('tutors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicRisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sgpa_trend', models.FloatField()),
                ('sgpa', models.FloatField()),
                ('name', models.CharField(max_length=200)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
    ]
