# Generated by Django 6.0 on 2026-02-21 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0003_attendancerisk'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
