# Generated by Django 6.0.3 on 2026-06-01 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0004_tutor_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='sem',
            field=models.CharField(choices=[('E', 'EVEN'), ('O', 'ODD')], default='O', max_length=1),
        ),
    ]
