# Generated by Django 6.0 on 2026-01-04 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_subject_alter_student_regno_semesterresult_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmark',
            name='total_max',
            field=models.IntegerField(default=0),
        ),
    ]
