# Generated by Django 6.0 on 2026-01-04 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_studentmark_total_max'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmark',
            name='total_max',
            field=models.IntegerField(),
        ),
    ]
