# Generated by Django 6.0 on 2026-02-04 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_subject_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmark',
            name='semester',
            field=models.IntegerField(default=1),
        ),
    ]
