# Generated by Django 6.0 on 2026-02-15 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_alter_studentmark_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmark',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.semesterresult'),
        ),
    ]
