# Generated by Django 6.0 on 2026-02-21 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='tutor_email',
            field=models.EmailField(default='teacher@gmail.com', max_length=255),
        ),
    ]
