# Generated by Django 6.0 on 2026-02-21 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_student_tutor_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='current_class',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
