# Generated by Django 6.0.3 on 2026-05-27 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0016_student_current_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='aadhaar',
            field=models.CharField(default='XXXXXXXXXXXX', max_length=12),
        ),
    ]
