# Generated by Django 6.0.3 on 2026-05-27 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0017_student_aadhaar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='sleep_hours',
        ),
        migrations.RemoveField(
            model_name='student',
            name='study_hours',
        ),
        migrations.RemoveField(
            model_name='student',
            name='toughness',
        ),
    ]
