# Generated by Django 6.0.3 on 2026-06-01 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0019_subject_subject_class_alter_subject_course_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subject_class',
            field=models.CharField(),
        ),
    ]
